#!/usr/bin/env python3
"""
PreCompact Hook: State Preservation
Saves critical state before context compaction.
"""

import sys
import json
from datetime import datetime
from pathlib import Path


def save_precompact_state(input_data: dict):
    """Save critical state before compaction."""
    state_file = Path('.claude/memory/precompact_state.md')

    try:
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        conversation_id = input_data.get('conversation_id', 'unknown')

        content = f"""# Pre-Compact State Snapshot

**Saved**: {timestamp}
**Conversation**: {conversation_id}

## Note
This file was auto-generated before a context compaction.
If you're resuming work and feel context was lost, check this file.

## Recovery Instructions
1. Read this file to understand where you left off
2. Read .claude/memory/active_context.md for current task
3. Read .claude/memory/session_log.md for recent history

---
*Auto-generated by precompact_save.py hook*
"""

        state_file.parent.mkdir(parents=True, exist_ok=True)
        state_file.write_text(content, encoding='utf-8')

        response = {
            "systemMessage": "[PreCompact] Critical state saved to .claude/memory/precompact_state.md"
        }
        print(json.dumps(response))
    except Exception:
        pass


def main():
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    hook_type = input_data.get('hook_type', '')
    if hook_type != 'PreCompact':
        sys.exit(0)

    save_precompact_state(input_data)
    sys.exit(0)


if __name__ == '__main__':
    main()
